addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.4.6")
addSbtPlugin("com.github.sbt" % "sbt-release"     % "1.1.0")
addSbtPlugin("org.scala-sbt"  % "sbt-autoversion" % "1.0.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"    % "3.9.20")
addSbtPlugin("com.github.sbt" % "sbt-pgp"         % "2.1.2")
